apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      region: IN
    matchExpressions:
      - { key: team, operator: In, values: [alpha,beta] }
  template:
    metadata:
      name: "webserer"
      labels:
        region: IN
        team: alpha
        app: v2
    spec:
      containers:
        - name: webserver
          image: pradeepkumar27/webserver-php:v1