apiVersion: v1
kind: ReplicationController
metadata:
  name: "myrc"
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: "mypod"
      labels:
        app: web
    spec:
      containers:
        - name: "my-web"
          image: "vimal13/apache-webserver-php"